const urls = {
  '.net': 'https://docs.microsoft.com/en-us/dotnet/',
  angular: 'https://angular.io/docs/ts/latest/',
  bash: 'https://www.gnu.org/software/bash/manual/bash.html',
  c: 'http://devdocs.io/c/',
  capistrano: 'https://github.com/capistrano/capistrano/tree/master/docs',
  capybara: 'http://www.rubydoc.info/github/jnicklas/capybara',
  coffeescript: 'http://coffeescript.org/',
  cpp: 'http://devdocs.io/cpp/',
  csharp: 'https://msdn.microsoft.com/en-us/library/kx37x362.aspx',
  css: 'http://cssreference.io/',
  cucumber: 'https://cucumber.io/docs',
  django: 'https://docs.djangoproject.com/en/1.11/',
  elixir: 'http://elixir-lang.org/docs.html',
  elm: 'http://elm-lang.org/docs',
  express: 'https://expressjs.com/en/api.html',
  git: 'https://git-scm.com/docs',
  go: 'https://golang.org/doc/',
  java: 'https://docs.oracle.com/javase/7/docs/api/',
  laravel: 'https://laravel.com/docs/5.4/installation',
  node: 'https://nodejs.org/en/docs/',
  phoenix: 'https://hexdocs.pm/phoenix/Phoenix.html',
  php: 'http://php.net/docs.php',
  play: 'https://www.playframework.com/documentation/2.5.x/Home',
  python: 'https://docs.python.org/3/',
  rails: 'http://api.rubyonrails.org/',
  ramda: 'http://ramdajs.com/docs/',
  react: 'https://facebook.github.io/react/docs/hello-world.html',
  redux: 'http://redux.js.org/',
  rspec: 'http://rspec.info/documentation/',
  ruby: 'http://ruby-doc.org/core-2.4.1/',
  rust: 'https://doc.rust-lang.org/',
  rxjs: 'http://reactivex.io/rxjs/',
  scala: 'http://docs.scala-lang.org/',
  symfony: 'http://symfony.com/doc/current/index.html',
  typescript: 'https://www.typescriptlang.org/docs/tutorial.html',
}

export default urls
